name: CI - Demo Capteurs

# Déclenche le pipeline à chaque push
on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest   # Machine Linux pour exécuter le job

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4   # Récupère le code du dépôt

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"     # Version de Python pour exécuter le script

      # Installe les dépendances si requirements.txt existe
      - name: Installer les dépendances
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Exécute le script principal pour générer le CSV
      - name: Exécuter la simulation de capteurs
        run: python main.py

      # Vérifie si le fichier CSV a été généré
      - name: Vérifier l'existence du CSV
        run: |
          test -f donnees.csv && echo "CSV OK" || (echo "CSV introuvable" && exit 1)

      # Publie le fichier CSV comme artefact
      - name: Publier l'artefact CSV
        uses: actions/upload-artifact@v4
        with:
          name: csv-genere
          path: donnees.csv
